name: Java CI with Maven + Security + Docker

on:
  push:
    branches: ["main"]
  pull_request:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/java-ci-sample

jobs:

  gitlint:
    name: Git Commit Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gitlint
        run: pip install gitlint
      - name: Run gitlint
        run: gitlint --commits "origin/main..HEAD"

  gitleaks:
    name: Scan for Secrets (GitLeaks)
    runs-on: ubuntu-latest
    needs: gitlint
    steps:
      - uses: actions/checkout@v4
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-path gitleaks-report.json

   
  build:
    name: Maven Build
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Maven Build Package
        run: mvn -B package --file pom.xml

  docker:
    name: Build & Scan Docker Image + Push
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ steps.meta.outputs.tags }} .

      - name: Scan Filesystem Vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          security-checks: vuln
          scan-ref: .
          format: table
          exit-code: 0

      - name: Scan Docker Image Vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: table
          exit-code: 0

      - name: Push Docker Image
        run: docker push ${{ steps.meta.outputs.tags }}
