name: Java CI with Maven + Security + Quality

on:
  push:
    branches: ["main"]
  pull_request:

jobs:

  gitlint:
    name: Git Commit Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gitlint
        run: |
          pip install gitlint
      - name: Run gitlint
        run: gitlint --commits "origin/main..HEAD"

  gitleaks:
    name: Scan for Secrets (GitLeaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --report-path gitleaks-report.json

  
  build:
    name: Maven Build
    needs: [ gitleaks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Maven Build Package
        run: mvn -B package --file pom.xml

  docker:
    name: Build & Push Docker Image + Trivy Scan
    needs: [build]
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: my-java-app

    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Scan vulnerabilities (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          security-checks: vuln
          scan-ref: .

      - name: Scan vulnerabilities (Docker Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_NAME:latest
          format: table
          vuln-type: os,library
          exit-code: 0

      - name: Push Docker Image (if clean)
        run: docker push $IMAGE_NAME:latest
